### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by brykko** [open-ephys-plugins/probe-viewer#1]
Hi, I just wondered if the plugin is ready for use yet? I'm running the "neuropix" branch of the GUI on Windows.

**Comment by kmichaelfox** [comment]
The plugin is not yet officially published because we still need more thorough testing on our end. Therefore, it is still considered experimental and stable performance cannot be assured. The safest course of action would be to wait until the plugin can be stress-tested, which ought to happen fairly soon.

However, I see no reason why you couldn't try it on your end. If you do try it out, please report your experience/bugs/issues here! I'll leave this issue open for that purpose.

**Comment by jsiegle** [comment]
Actually, the `neuropix` branch is based on an older version of the GUI, while the probe viewer plugin in based on the current `development` branch. I'll need to make the `neuropix` branch compatible with these changes before the new visualizations can be used. I'm planning to do this (as well as update the GUI for use with the Phase IIIb probes) before the end of the year.

**Comment by brykko** [comment]
Thanks for the information, I'll wait for a couple of months until these updates are ready.
